config/routes.rb
FbBgbng::Application.routes.draw do  

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => {:sessions => 'sessions'}

 
  resources :classifieds, :profile

  match '/facebook/login' => 'facebook#login', :as => :facebook_login
  match '/regions/:id' => 'regions#index', :as => :region
  match '/regions/:region_id/categories/:id' => 'categories#index', :as => :category
  match '/account' => 'accounts#index', :as => :account
  match '/search' => 'searches#index', :as => :search
  match '/facebook_callback' => 'facebook#callback', :as => :facebook_callback
  match '/logout' => 'facebook#logout', :as => :destroy_user_session

  root :to => 'pages#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= full_title(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= yield :javascripts %>  
  <%= csrf_meta_tags %>
</head>
<body>
<div id="fb-root"></div>
<div class="container">
  <%= render 'shared/flash_messages' unless flash.blank? %>
  <div class="row-fluid">
    <div class="span4">
      <h1><%= link_to 'Classifieds', root_path %></h1>
    </div>
    <div class="span4 new_classified">
      <%= link_to 'Add Classified', new_classified_path, :class => 'btn btn-warning btn-large'%>
    </div>
    <div class="span4 search">
      <%= form_tag '/search', :class => 'form-search', :id => "classifieds_search", :method => :get do %>
        <%= text_field_tag :query, nil, :value => params[:query], :class => 'input-small' %>
        <%= hidden_field_tag :region_id, nil, :value => params[:id].blank? ? params[:region_id] : params[:id], :class => 'input-small' %>
        <%= submit_tag :Search, :name => nil, :class => 'btn' %>
      <% end %>
    </div>
  </div>	 
  <div class="row-fluid">  	
    <div class="span9">
      <%= yield %>
    </div>
    <div class="span3 navigation">
      <div class="account">
      	<%= link_to 'Home', root_path %> 
      	<% if user_signed_in? %>
	      	| <%= link_to 'My Classifieds', account_path %>
	        | <%= link_to 'Profile', profile_path(current_user) %>
	        <% if current_user.has_role? :admin %>
	        | <%= link_to 'Admin', '/admin' %> 
	      	<% end %>
      	<% end %>
      </div>
      <iframe src="https://www.facebook.com/plugins/like.php?href=http://0.0.0.0:6665/&amp;send=false&amp;layout=button_count&amp;show_faces=false&amp;action=like&amp;appId="
        scrolling="no" frameborder="0"
        style="border:none; width:75px; height:25px; overflow:hidden;" allowTransparency="true">
      </iframe><br />
      <%#= facebook_login_button('small') %>
      <% if user_signed_in? %>
      	Welcome <%= current_user.name %>, <%= link_to image_tag("fb-logout.gif"), "#", :id => "facebook_logout" %>      	
      <% else %>
      	<%= link_to image_tag("facebook-login.jpeg"), FacebookApi.facebook_oauth_url, :id => "facebook_login" %>
      <% end %>
    </div>
  </div>
</div>
</body>
</html>
<script>
  window.fbAsyncInit = function() {
    FB.init({appId: <%= FACEBOOK_APP_ID %>, status: true, cookie: true, xfbml: true});
  };
  (function() {
    var e = document.createElement('script');
    e.type = 'text/javascript';
    e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
    e.async = true;
    document.getElementById('fb-root').appendChild(e);
  }());
</script>