config/routes.rb
FbBgbng::Application.routes.draw do  

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => {:sessions => 'sessions'}

 
  resources :classifieds, :profile

  match '/facebook/login' => 'facebook#login', :as => :facebook_login
  match '/regions/:id' => 'regions#index', :as => :region
  match '/regions/:region_id/categories/:id' => 'categories#index', :as => :category
  match '/account' => 'accounts#index', :as => :account
  match '/search' => 'searches#index', :as => :search
  match '/facebook_callback' => 'facebook#callback', :as => :facebook_callback
  match '/logout' => 'facebook#logout', :as => :destroy_user_session

  root :to => 'pages#index'
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @classifieds = Classified.where(:user_id => current_user.id)
  end
end

app/views/accounts/index.html.erb
<h2>My Classifieds</h2>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Published</th>
    <th>Region</th>
    <th>Category</th>
    <th></th>
  </tr>
  <% @classifieds.each do |classified| %>
  <tr>
    <td><%= link_to classified.name, classified %></td>
    <td><%= (classified.publish) ? 'Yes' : 'No' %></td>
    <td><%= classified.region.name %></td>
    <td><%= classified.category.name %></td>
    <td><%= (link_to 'Edit', edit_classified_path(classified)) if current_user.id == classified.user_id %></td>
  </tr>
  <% end %>
</table>